package gn_righthand;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;



public class gui_SelectionScreen extends javax.swing.JFrame {
    
    //VARIABLES DECLARATION
    private String sUser = "";//User's Oracle e-mail
    private String sPass = "";//Encrypted SSO password    
    private String sVER = "";
    private boolean bONLINE = false;
    private String sName = "";
    private String sPriv = "";
    
    //CONSTRUCTORS
    public gui_SelectionScreen(boolean bONLINE, String sUser, String sPass, String sVer, String sName, String sPriv) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.sUser = sUser;
        this.sPass = sPass;
        this.bONLINE = bONLINE;
        this.sVER = sVer;
        this.sName = sName;
        this.sPriv = sPriv;
        
        
        setTitle("GOOD-NEW RIGHTHAND");
        jlblTop.setText("GN-RIGHTHAND "+ sVER.substring(0,4));
        jlblUser.setText("<html>Welcome <font color='blue'>" + this.sName.substring(0,this.sName.indexOf(' ')) + "</font>. Please select your task for today: </html>");
        System.out.println("Index: " + this.sName.indexOf(' '));
        
        jlblLeftInfo.setText("<html>Load a list of Parts and Orgs from Excel.<br>"
                + "Filter the data and create potential consults for GB parts.<br>"
                + "While looking for parts, see related acitve tasks.<br>"
                + "Get warnings about previous consults to avoid spam.<br>"
                + "Send several mails at once with a simple click.<br>"
                + "</html>");
        jlblRigtInfo.setText("<html>Manage and control the <font color='blue'>Data Bases</font>.<br>"
                + "Search for, add, delete or update lines.<br>"
                + "Mail <font color='blue'>Consults</font> Data Base.<br>"
                + "<font color='blue'>Backorders</font> Data Base.<br>"
                + "<font color='blue'>WebADI</font> orders Data Base.<br>"
                + "</html>");
        
        setaccessLevel();
    }

    private gui_SelectionScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    //Restrics access to different options depending on the User level privilege
    private void setaccessLevel(){
    //<editor-fold defaultstate="collapsed" desc="Method Source Code">
        switch ( sPriv ){
            case "Reader" :{
                this.jbtnCon.setEnabled(false);
                break;
            }
            case "Offline" :{
                this.jbtnCon.setEnabled(false);
                break;
            }
        }
    }
    //</editor-fold>
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpnlTop = new javax.swing.JPanel();
        jlblTop = new javax.swing.JLabel();
        jpnlBottom = new javax.swing.JPanel();
        jlblCreationDate = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();
        jpnlMidLef = new javax.swing.JPanel();
        jbtnCon = new javax.swing.JButton();
        jlblLeft = new javax.swing.JLabel();
        jlblLeftInfo = new javax.swing.JLabel();
        jpnlMidRig = new javax.swing.JPanel();
        jbtnDBs = new javax.swing.JButton();
        jlblRigt = new javax.swing.JLabel();
        jlblRigtInfo = new javax.swing.JLabel();
        jlblUser = new javax.swing.JLabel();
        jlblSta = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblTop.setFont(new java.awt.Font("Vacation Postcard NF", 1, 34)); // NOI18N
        jlblTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTop.setText("GN-righthand x.xx");
        jlblTop.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlblTop.setIconTextGap(8);

        javax.swing.GroupLayout jpnlTopLayout = new javax.swing.GroupLayout(jpnlTop);
        jpnlTop.setLayout(jpnlTopLayout);
        jpnlTopLayout.setHorizontalGroup(
            jpnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlTopLayout.setVerticalGroup(
            jpnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnlBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblCreationDate.setText("Oracle Spares Planning Team, Costa Rica, 2017.");

        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_medium.png"))); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setToolTipText("Exit the application");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlBottomLayout = new javax.swing.GroupLayout(jpnlBottom);
        jpnlBottom.setLayout(jpnlBottomLayout);
        jpnlBottomLayout.setHorizontalGroup(
            jpnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblCreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlBottomLayout.setVerticalGroup(
            jpnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCreationDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlBottomLayout.createSequentialGroup()
                        .addComponent(jbtnExit)
                        .addContainerGap())))
        );

        jpnlMidLef.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnCon.setText("NEW CONSULTS ENGINE");
        jbtnCon.setToolTipText("");
        jbtnCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConActionPerformed(evt);
            }
        });

        jlblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New_Consults_LIL.jpg"))); // NOI18N

        javax.swing.GroupLayout jpnlMidLefLayout = new javax.swing.GroupLayout(jpnlMidLef);
        jpnlMidLef.setLayout(jpnlMidLefLayout);
        jpnlMidLefLayout.setHorizontalGroup(
            jpnlMidLefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMidLefLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlMidLefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblLeftInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlMidLefLayout.setVerticalGroup(
            jpnlMidLefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMidLefLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblLeftInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnlMidRig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnDBs.setText("DATA BASE MANAGER");
        jbtnDBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDBsActionPerformed(evt);
            }
        });

        jlblRigt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data_Base_LIL.jpg"))); // NOI18N

        javax.swing.GroupLayout jpnlMidRigLayout = new javax.swing.GroupLayout(jpnlMidRig);
        jpnlMidRig.setLayout(jpnlMidRigLayout);
        jpnlMidRigLayout.setHorizontalGroup(
            jpnlMidRigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMidRigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlMidRigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRigt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnDBs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblRigtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlMidRigLayout.setVerticalGroup(
            jpnlMidRigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMidRigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnDBs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblRigt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblRigtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlblUser.setText("User");

        jlblSta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblSta.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlMidLef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnlMidRig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblUser)
                    .addComponent(jlblSta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlMidLef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlMidRig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        int opc = JOptionPane.showConfirmDialog(this,"Do you want to exit the Application?\n");
        if ( opc == 0 ){
            //updateConsultsTXTDataBase();
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        gui_MainScreen guiMS = new gui_MainScreen(1, bONLINE, sUser, sPass, sVER,sName, sPriv);
        if ( bONLINE == true ){
            guiMS.jlblSta.setForeground(Color.BLACK);
            guiMS.jlblSta.setBackground(new Color(125,245,10));
            guiMS.jlblSta.setText("ONLINE");
        }
        else{
            guiMS.jlblSta.setForeground(Color.WHITE);
            guiMS.jlblSta.setBackground(new Color(255,50,0));
            guiMS.jlblSta.setText("OFFLINE");
        }
        guiMS.setLocationRelativeTo(this);
        guiMS.setVisible(true);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
        
        
    }//GEN-LAST:event_jbtnConActionPerformed

    private void jbtnDBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDBsActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        gui_MainScreen guiMS = new gui_MainScreen(2, bONLINE, sUser, sPass, sVER, sName, sPriv);
        if ( bONLINE == true ){
            guiMS.jlblSta.setForeground(Color.BLACK);
            guiMS.jlblSta.setBackground(new Color(125,245,10));
            guiMS.jlblSta.setText("ONLINE");
        }
        else{
            guiMS.jlblSta.setForeground(Color.WHITE);
            guiMS.jlblSta.setBackground(new Color(255,50,0));
            guiMS.jlblSta.setText("OFFLINE");
        }
        guiMS.setLocationRelativeTo(this);
        guiMS.setVisible(true);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        dispose();
    }//GEN-LAST:event_jbtnDBsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_SelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_SelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_SelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_SelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_SelectionScreen().setVisible(true);
            }
        });
    }
    
    //<editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnCon;
    private javax.swing.JButton jbtnDBs;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JLabel jlblCreationDate;
    private javax.swing.JLabel jlblLeft;
    private javax.swing.JLabel jlblLeftInfo;
    private javax.swing.JLabel jlblRigt;
    private javax.swing.JLabel jlblRigtInfo;
    public javax.swing.JLabel jlblSta;
    private javax.swing.JLabel jlblTop;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JPanel jpnlBottom;
    private javax.swing.JPanel jpnlMidLef;
    private javax.swing.JPanel jpnlMidRig;
    private javax.swing.JPanel jpnlTop;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
